spring:
  application:
    name: loan-management-system
  
  datasource:
    url: jdbc:postgresql://localhost:5432/obi
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
jwt:
  secret: mySecretKeyForStateLoanManagementSystemThatIsVeryLongAndSecure123456789
  expiration: 86400000 # 24 hours in milliseconds

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Logging
logging:
  level:
    com.stateloan.lms: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG